config/routes.rb
Rails.application.routes.draw do
  
  resources :surveys
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'
  resources :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers, :dependent => :delete_all
  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank?}, :allow_destroy => true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_paper_trail
  has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6, maxinum: 16}, allow_blank: true, on: :update

  attr_encrypted :ssn_number, key: ::ENCRYPTED_KEY, attribute: 'encrypted_ssn_number'
  attr_encrypted :ssn_card, key: ::ENCRYPTED_KEY 

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticate?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  layout nil
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user

      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  layout nil
  def new
    @survey = Survey.new
    2.times do
      question = @survey.questions.build
      question.answers.build
    end
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      flash[:notice] = "Successfully create survey"
      redirect_to @survey
    else
      render :action => new
    end
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def update
  end

  def edit
  end

  private

  def survey_params
    params.require(:survey).permit(:name,
                                   questions_attributes: [:id, :content, :_destroy, answers_attributes: [:content, :_destroy]])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by(id: user_id)
      if user && user.authenticate?(cookies[:remember_token])
        log_in user
        remember user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
  def link_to_add_fields(name, builder, association, **options)
    new_object = builder.object.send(association).build
    fields = builder.fields_for(association, new_object, :child_index => new_object.id) do |sub_builder|
      render "#{association.to_s.singularize}_fields", f: sub_builder
    end

    options.merge!(data: { id: new_object.id, fields: fields.gsub("\n", "")  })
    link_to name, "#", **options

  end

  def link_to_remove_fields(name, builder, **options)
    f_hidden =  builder.hidden_field(:_destroy)

    options.merge!(data: {id: Time.now.to_i ,fields: f_hidden.gsub("\n", "")  })

    link_to name, "#", **options
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <!--<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "my app", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   '#' %></li>
            <li><%= link_to "Help",   '#' %></li>
            <li><%= link_to "Log in", login_path %></li>
          </ul>
        </nav>
      </div>
    </header>-->
    <div class="container">
       <% flash.each do |message_type, message| %>
         <div class="alert alert-<%= message_type %>"><%= message %></div>
       <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<%= provide(:title, "About")%>
<h1>About</h1>
<p>Find me in app/views/static_pages/about.html.erb
  <a href="http://www.railstutorial.org/#about">Rails Tutorial help section</a>
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>
</p>

app/views/static_pages/help.html.erb
<%= provide(:title, "Help")%>
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/surveys/_answer_fields.html.haml
%p
  = f.label :content, "Answer"
  = f.text_field :content
  = link_to_remove_fields "remove", f,class: "remove answer"

app/views/surveys/_question_fields.html.haml
.questions
  %p{class: "panel"}
    = f.label :content, "Question"
    = f.text_area :content, :rows => 3
    = f.check_box :_destroy
    = f.label :_destroy, "remove question"

  .answer
    = f.fields_for :answers do |builder|
      = render 'answer_fields', :f => builder
    .add_link
      = link_to_add_fields "+Add", f, "answers", class: "add_answer"

app/views/surveys/_sub_surveys.html.haml
%p
  = f.label :name
  = f.text_field :name
%p
= f.fields_for :questions do |builder|
  = render "question_fields", :f => builder
%p
  = f.submit "submit"

app/views/surveys/create.html.erb
<h1>Survey#create</h1>
<p>Find me in app/views/survey/create.html.erb</p>

app/views/surveys/edit.html.erb
<h1>Survey#edit</h1>
<p>Find me in app/views/survey/edit.html.erb</p>

app/views/surveys/new.html.haml
.test
  .test1
    %h1 hello
    %h1 hello
    %h2 hello
  .test2
    =form_for @survey do |f|
      = flash[:notice]
      = render partial: 'sub_surveys' , locals: {f: f}

:javascript
  $(function(){
    $('form').on('click', '.add_answer', function(event){
       var id = $(this).data("id")
       var fields = $(this).data("fields")
       var time = new Date().getTime()
       var regexp = new RegExp(id, 'g')
       $(this).parent().before(fields.replace(regexp, time))
       event.preventDefault()
    })
  })

app/views/surveys/show.html.haml
.test1
  %h1 hello
  %h1 hello
  %h2 hello
  .test2
    %p
      %strong Name:
      = h @survey.name

    %ol
      - @survey.questions.each do |question|
        %li
          = h question.content
          %ul
            - for answer in question.answers
              %li 
                = h answer.content

    %p
      = link_to "Edit", edit_survey_path(@survey)
      = link_to "Destroy", @survey, :confirm => 'Are you sure?', :method => :delete |
      = link_to "View All", surveys_path

app/views/surveys/update.html.erb
<h1>Survey#update</h1>
<p>Find me in app/views/survey/update.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="col-md-6 col-md-offser-3">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Create my account", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>